### ISSUE TITLE
Make an ADS dev key with astropy.team@gmail.com?

### ISSUE THREAD

**Issue by adrn** [adrn/astropy-sustainability#2]
Right now, I'm using my own API key...

**Comment by adrn** [comment]
Not sure who has the email login -- I think one of @astrofrog @eteq @kelle @taldcroft will have to do this?

**Comment by kelle** [comment]
I can help. Please DM me on Slack.

**Comment by kelle** [comment]
ADS login for astropy.team@gmail.com and Key are both generated. Key sent to adrian via Slack DM. Info stored in team 1Password account. Documenting who has access to that account is in [project/#115](https://github.com/astropy/project/issues/115). (I think this issue can be closed.)

**Comment by adrn** [comment]
New key added to the repo - thanks @kelle !
